export const GET_ITEM_REQUEST = 'GET_ITEM_REQUEST'
export const GET_ITEM_SUCCESS = 'GET_ITEM_SUCCESS'
export const GET_ITEM_FAILURE = 'GET_ITEM_FAILURE'

export const POST_ITEM_REQUEST = 'POST_ITEM_REQUEST'
export const POST_ITEM_SUCCESS = 'POST_ITEM_SUCCESS'
export const POST_ITEM_FAILURE = 'POST_ITEM_FAILURE'
