// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using RestauranteApi.Infra.Context;
using System;

namespace RestauranteApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("RestauranteApi.Infra.Entity.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Categoria");

                    b.Property<string>("Descricao");

                    b.Property<string>("Titulo");

                    b.Property<string>("UrlImagem");

                    b.Property<decimal>("Valor");

                    b.HasKey("Id");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("RestauranteApi.Infra.Entity.ItemPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ItemId");

                    b.Property<int?>("PedidoId");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("PedidoId");

                    b.ToTable("ItemPedido");
                });

            modelBuilder.Entity("RestauranteApi.Infra.Entity.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Data");

                    b.Property<int>("Mesa");

                    b.Property<string>("Nome");

                    b.Property<string>("Resumo");

                    b.HasKey("Id");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("RestauranteApi.Infra.Entity.ItemPedido", b =>
                {
                    b.HasOne("RestauranteApi.Infra.Entity.Item", "Item")
                        .WithMany("ItemPedido")
                        .HasForeignKey("ItemId");

                    b.HasOne("RestauranteApi.Infra.Entity.Pedido", "Pedido")
                        .WithMany("ItemPedido")
                        .HasForeignKey("PedidoId");
                });
#pragma warning restore 612, 618
        }
    }
}
